### ISSUE TITLE
Asynchronous video upload can lead to several ffmpeg processes simultaneously

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/mogi-server#38]
When uploading the video, we send the request response after creating the video in the database and before the ffmpeg process.

Since we might have several ffmpeg process from several user's upload, we must make it more synchronous. 

Send the request response after ffmpeg finishes processing the video

**Comment by martelli** [comment]
The response is now sent after the video has been processed and the information is successfully stored into the database.
