### ISSUE TITLE
Upload of multiple videos fails when files are sent after the server has been restarted

### ISSUE THREAD

**Issue by martelli** [igarape/mogi-server#41]
When multiple videos are recorded on the mobile, the upload will fail if the server has been restarted *after* the user logon. In this case, multiple empty files will appear on the upload folder.

**Comment by ebadran** [comment]
Also, data upload (from the smartphones to the servers) is not working well when the precinct’s Wi-Fi connection is too slow or intermittent. An upload connection time-out must be enabled to improve resilience.
If upload fails, a notification to the user and/or the admin may be sent.

**Comment by brunosiqueira** [comment]
In the app, when we have an Unauthorized response, we must force the login again

**Comment by martelli** [comment]
As the upload code has evolved, this issue seems to be fixed cannot be reproduced.
