### ISSUE TITLE
Log Audit Report

### ISSUE THREAD

**Issue by ebadran** [igarape/mogi-server#47]
Create a Log Audit Report using an append­-only data format to reduce the risk of tampering.
The system will produce an automated weekly report on access patterns across the set of approved individuals.

The report may also be generated by users with Levels 1 and 2 Access at any time.
The command to generate the report may be given from the "Admin Button" drop-down menu:

![screen shot 2015-10-21 at 19 23 18](https://cloud.githubusercontent.com/assets/12832304/10650845/93df887a-782a-11e5-97cc-02ce5a3141ad.png)

A pop-up box will appear asking to select the date period and the name of the user group for the report. There must be an option for "selecting all groups" in case the user has access to more than one group.

The report includes:

1. How much total footage, by time and number of distinct pieces, has each user viewed in the last week;

2. How much footage o​utside of known incidents,​ by time and number of distinct pieces, has each user viewed in the last week;

3. Exact information on what videos have been exported within the last week;

4. The hours of footage logged;

5. The hours of footage accessed.

**Comment by jkosslyn** [comment]
worth moving to a milestone?

**Comment by brunosiqueira** [comment]
This is an adaptation of the current Cape Town Use report

**Comment by jkosslyn** [comment]
nice!

Justin

Justin Kosslyn | Product Manager, Google Ideas <http://google.com/ideas> |
jkosslyn@google.com

**Comment by brunosiqueira** [comment]
related to igarape/copcast-admin#164
